### ISSUE TITLE
Bugs when set MXNET_CPU_WORKER_NTHREADS > 1

### ISSUE THREAD

**Issue by neuzxy** [ralzq01/RDMA-MXNet-ps-lite#1]
Hi, Thanks for your work. 

I built MXNet 1.1.0 using `RDMA-MXNet-ps-lite`, it works well use MXNet official code examples. 

But when I set `MXNET_CPU_WORKER_NTHREADS>1 (default=1)indicates the maximum number of scheduling threads on CPU`  to train distributed resnet-v1-50 or other models(even mnist)  to improve performance. It works in the official MXNet version, with ps-lite based on ZMQ. But I find some strange situation in the RDMA version, the result is in random. 

1. Program deadlock. I use `strace -p pid` and and see `FUTEX_WAIT_PRIVATE`. 
2. RDMA ibv_post_send error. `[1] RDMA Post Send failed. Exit Code: 12`. According to the source code of ib, `ENOMEM  = 12 /* not enough space */`. 

**Our environment is 4 nodes each with 512G memory and 8 * NVIDIA Tesla V100.**

I see you propose 3 models and use model 3 in the pdf. Each QP has its own registered send buffer and receive buffer. 

**I suppose it maybe not thread safe when CPU read/write the send/receive buffer in the RDMA implementations. Does it the cause of this problem?**

Thanks.

**Comment by zhiqi-0** [comment]
Hi, sorry for troubling you. 

RDMA version on `ps-lite` now has an official version. Please check out here: [ps-lite-rdma](https://github.com/dmlc/ps-lite/pull/124)

Your assumption maybe true. We didn't test on setting where `MXNET_CPU_WORKER_NTHREADS>1`. In our codes, we didn't check whether recv buffers' messages are consumed by `ps-lite`. So this may be a potential bug in the code. When writing this code, we were new to RDMA, and now I have been leaving this area for almost one year. So I'm really sorry that I couldn't help you get detailed information about this error.

To be honest, these codes are just for competition on RDMA coding. We didn't do strict test on these codes. So there may exist lots of threading relevant problems. And these codes are no longer maintained after this competition.

**Comment by neuzxy** [comment]
Thanks, I'll try the official pr.
